# Generated by Django 3.0.6 on 2020-06-11 06:15

from django.db import migrations, models
import ingredients.models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=ingredients.models.upload_path),
        ),
    ]
