# Generated by Django 3.0.6 on 2020-06-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredients_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
