# Generated by Django 3.0.6 on 2020-06-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlans_gain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('strMeal', models.CharField(default='None', max_length=100)),
                ('strInstructions', models.CharField(default='None', max_length=3000)),
                ('img', models.CharField(default='None', max_length=200)),
                ('strIngredient1', models.CharField(blank=True, default='None', max_length=100)),
                ('strIngredient2', models.CharField(blank=True, default='None', max_length=100)),
                ('strIngredient3', models.CharField(blank=True, default='None', max_length=100)),
                ('strIngredient4', models.CharField(blank=True, default='None', max_length=100)),
                ('strIngredient5', models.CharField(blank=True, default='None', max_length=100)),
                ('strIngredient6', models.CharField(blank=True, default='None', max_length=100)),
                ('strIngredient7', models.CharField(blank=True, default='None', max_length=100)),
                ('strIngredient8', models.CharField(blank=True, default='None', max_length=100)),
                ('strIngredient9', models.CharField(blank=True, default='None', max_length=100)),
                ('strIngredient10', models.CharField(blank=True, default='None', max_length=100)),
                ('strIngredient11', models.CharField(blank=True, default='None', max_length=100)),
                ('strIngredient12', models.CharField(blank=True, default='None', max_length=100)),
                ('strIngredient13', models.CharField(blank=True, default='None', max_length=100)),
                ('strIngredient14', models.CharField(blank=True, default='None', max_length=100)),
                ('strIngredient15', models.CharField(blank=True, default='None', max_length=100)),
                ('strIngredient16', models.CharField(blank=True, default='None', max_length=100)),
                ('strIngredient17', models.CharField(blank=True, default='None', max_length=100)),
                ('strIngredient18', models.CharField(blank=True, default='None', max_length=100)),
                ('strIngredient19', models.CharField(blank=True, default='None', max_length=100)),
                ('strIngredient20', models.CharField(blank=True, default='None', max_length=100)),
                ('strMeasure1', models.CharField(default='None', max_length=100)),
                ('strMeasure2', models.CharField(default='None', max_length=100)),
                ('strMeasure3', models.CharField(default='None', max_length=100)),
                ('strMeasure4', models.CharField(default='None', max_length=100)),
                ('strMeasure5', models.CharField(default='None', max_length=100)),
                ('strMeasure6', models.CharField(default='None', max_length=100)),
                ('strMeasure7', models.CharField(default='None', max_length=100)),
                ('strMeasure8', models.CharField(default='None', max_length=100)),
                ('strMeasure9', models.CharField(default='None', max_length=100)),
                ('strMeasure10', models.CharField(default='None', max_length=100)),
                ('strMeasure11', models.CharField(default='None', max_length=100)),
                ('strMeasure12', models.CharField(default='None', max_length=100)),
                ('strMeasure13', models.CharField(default='None', max_length=100)),
                ('strMeasure14', models.CharField(default='None', max_length=100)),
                ('strMeasure15', models.CharField(default='None', max_length=100)),
                ('strMeasure16', models.CharField(default='None', max_length=100)),
                ('strMeasure17', models.CharField(default='None', max_length=100)),
                ('strMeasure18', models.CharField(default='None', max_length=100)),
                ('strMeasure19', models.CharField(default='None', max_length=100)),
                ('strMeasure20', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
