from django.db import models
from django.utils import timezone
# from users.models import User


class MealPlan(models.Model):

    id = models.AutoField(primary_key=True)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    strMeal = models.CharField(default="None", max_length=100)
    strInstructions = models.CharField(default="None", max_length=3000)
    strMealThumb = models.CharField(default="None", max_length=100)
    strIngredient1 = models.CharField(default="None", max_length=100)
    strIngredient2 = models.CharField(default="None", max_length=100)
    strIngredient3 = models.CharField(default="None", max_length=100)
    strIngredient4 = models.CharField(default="None", max_length=100)
    strIngredient5 = models.CharField(default="None", max_length=100)
    strIngredient6 = models.CharField(default="None", max_length=100)
    strIngredient7 = models.CharField(default="None", max_length=100)
    strIngredient8 = models.CharField(default="None", max_length=100)
    strIngredient9 = models.CharField(default="None", max_length=100)
    strIngredient10 = models.CharField(default="None", max_length=100)
    strIngredient11 = models.CharField(default="None", max_length=100)
    strIngredient12 = models.CharField(default="None", max_length=100)
    strIngredient13 = models.CharField(default="None", max_length=100)
    strIngredient14 = models.CharField(default="None", max_length=100)
    strIngredient15 = models.CharField(default="None", max_length=100)
    strIngredient16 = models.CharField(default="None", max_length=100)
    strIngredient17 = models.CharField(default="None", max_length=100)
    strIngredient18 = models.CharField(default="None", max_length=100)
    strIngredient19 = models.CharField(default="None", max_length=100)
    strIngredient20 = models.CharField(default="None", max_length=100)
    intMeasure1 = models.IntegerField(default = 0)
    intMeasure2 = models.IntegerField(default = 0)
    intMeasure3 = models.IntegerField(default = 0)
    intMeasure4 = models.IntegerField(default = 0)
    intMeasure5 = models.IntegerField(default = 0)
    intMeasure6 = models.IntegerField(default = 0)
    intMeasure7 = models.IntegerField(default = 0)
    intMeasure8 = models.IntegerField(default = 0)
    intMeasure9 = models.IntegerField(default = 0)
    intMeasure10 = models.IntegerField(default = 0)
    intMeasure11 = models.IntegerField(default = 0)
    intMeasure12 = models.IntegerField(default = 0)
    intMeasure13 = models.IntegerField(default = 0)
    intMeasure14 = models.IntegerField(default = 0)
    intMeasure15 = models.IntegerField(default = 0)
    intMeasure16 = models.IntegerField(default = 0)
    intMeasure17 = models.IntegerField(default = 0)
    intMeasure18 = models.IntegerField(default = 0)
    intMeasure19 = models.IntegerField(default = 0)
    intMeasure20  = models.IntegerField(default = 0)
