from django.db import models
from django.utils import timezone
# from users.models import User


class MealPlan(models.Model):
<<<<<<< HEAD
    idMeal = models.AutoField(primary_key=True)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    strMeal = models.CharField(default="None", max_length=100)
    strInstructions = models.CharField(default="None", max_length=3000)
    strMealThumb = models.CharField(default="None", max_length=100)
    strIngredient1 = models.CharField(default="None", max_length=100)
    strIngredient2 = models.CharField(default="None", max_length=100)
    strIngredient3 = models.CharField(default="None", max_length=100)
    strIngredient4 = models.CharField(default="None", max_length=100)
    strIngredient5 = models.CharField(default="None", max_length=100)
    strIngredient6 = models.CharField(default="None", max_length=100)
    strIngredient7 = models.CharField(default="None", max_length=100)
    strIngredient8 = models.CharField(default="None", max_length=100)
    strIngredient9 = models.CharField(default="None", max_length=100)
    strIngredient10 = models.CharField(default="None", max_length=100)
    strIngredient11 = models.CharField(default="None", max_length=100)
    strIngredient12 = models.CharField(default="None", max_length=100)
    strIngredient13 = models.CharField(default="None", max_length=100)
    strIngredient14 = models.CharField(default="None", max_length=100)
    strIngredient15 = models.CharField(default="None", max_length=100)
    strIngredient16 = models.CharField(default="None", max_length=100)
    strIngredient17 = models.CharField(default="None", max_length=100)
    strIngredient18 = models.CharField(default="None", max_length=100)
    strIngredient19 = models.CharField(default="None", max_length=100)
    strIngredient20 = models.CharField(default="None", max_length=100)
    strMeasure1 = models.IntegerField(default = 0)
    strMeasure2 = models.IntegerField(default = 0)
    strMeasure3 = models.IntegerField(default = 0)
    strMeasure4 = models.IntegerField(default = 0)
    strMeasure5 = models.IntegerField(default = 0)
    strMeasure6 = models.IntegerField(default = 0)
    strMeasure7 = models.IntegerField(default = 0)
    strMeasure8 = models.IntegerField(default = 0)
    strMeasure9 = models.IntegerField(default = 0)
    strMeasure10 = models.IntegerField(default = 0)
    strMeasure11 = models.IntegerField(default = 0)
    strMeasure12 = models.IntegerField(default = 0)
    strMeasure13 = models.IntegerField(default = 0)
    strMeasure14 = models.IntegerField(default = 0)
    strMeasure15 = models.IntegerField(default = 0)
    strMeasure16 = models.IntegerField(default = 0)
    strMeasure17 = models.IntegerField(default = 0)
    strMeasure18 = models.IntegerField(default = 0)
    strMeasure19 = models.IntegerField(default = 0)
    strMeasure20  = models.IntegerField(default = 0)
=======
    id = models.AutoField(primary_key=True)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    mealName = models.CharField(default="None", max_length=100)
    kcal = models.IntegerField(default=0, max_length=10)
    carbonhydrate = models.IntegerField(default=0, max_length=10)
    protein = models.IntegerField(default=0, max_length=10)
    fat = models.IntegerField(default=0, max_length=10)
    sodium = models.IntegerField(default=0, max_length=10)
    vitaminc = models.IntegerField(default=0, max_length=10)
>>>>>>> Chris
    # delcreateddate = models.DateTimeField(auto_now_add=True)
    #mealType = models.CharField(default="None", max_length=100)
    # User = To whom belongs this delivery (=> cross reference to items)
    # items = reference to Shopping list and make a list out of it
