# Generated by Django 3.0.6 on 2020-06-01 07:25

from django.db import migrations, models
import mealplans.models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=mealplans.models.upload_path),
        ),
    ]
