# Generated by Django 3.0.6 on 2020-06-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0005_auto_20200611_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='strMeasure1',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strMeasure10',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strMeasure11',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strMeasure12',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strMeasure13',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strMeasure14',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strMeasure15',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strMeasure16',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strMeasure17',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strMeasure18',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strMeasure19',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strMeasure2',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strMeasure20',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strMeasure3',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strMeasure4',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strMeasure5',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strMeasure6',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strMeasure7',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strMeasure8',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strMeasure9',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
