# Generated by Django 3.0.6 on 2020-06-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='None', max_length=100)),
                ('img', models.CharField(default='None', max_length=100)),
                ('kcal', models.DecimalField(decimal_places=5, max_digits=10)),
                ('protein', models.DecimalField(decimal_places=5, max_digits=10)),
                ('fat', models.DecimalField(decimal_places=5, max_digits=10)),
                ('carbohydrate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('sodium', models.DecimalField(decimal_places=5, max_digits=10)),
                ('vitaminc', models.DecimalField(decimal_places=5, max_digits=10)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('origin', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
