# Generated by Django 3.0.6 on 2020-06-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='carbohydrate',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='img',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='kcal',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='name',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='sodium',
        ),
        migrations.AlterField(
            model_name='meals',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
