# Generated by Django 3.0.6 on 2020-06-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_auto_20200613_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meals',
            old_name='strMeasure1',
            new_name='intMeasure1',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='strMeasure10',
            new_name='intMeasure10',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='strMeasure11',
            new_name='intMeasure11',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='strMeasure12',
            new_name='intMeasure12',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='strMeasure13',
            new_name='intMeasure13',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='strMeasure14',
            new_name='intMeasure14',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='strMeasure15',
            new_name='intMeasure15',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='strMeasure16',
            new_name='intMeasure16',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='strMeasure17',
            new_name='intMeasure17',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='strMeasure18',
            new_name='intMeasure18',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='strMeasure19',
            new_name='intMeasure19',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='strMeasure2',
            new_name='intMeasure2',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='strMeasure20',
            new_name='intMeasure20',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='strMeasure3',
            new_name='intMeasure3',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='strMeasure4',
            new_name='intMeasure4',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='strMeasure5',
            new_name='intMeasure5',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='strMeasure6',
            new_name='intMeasure6',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='strMeasure7',
            new_name='intMeasure7',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='strMeasure8',
            new_name='intMeasure8',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='strMeasure9',
            new_name='intMeasure9',
        ),
    ]
