# Generated by Django 3.0.6 on 2020-05-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='None', max_length=100)),
                ('mealType', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
