# Generated by Django 3.0.6 on 2020-06-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0003_auto_20200607_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
