# Generated by Django 3.0.6 on 2020-06-13 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mealplans', '0007_auto_20200613_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplan',
            old_name='strMeal',
            new_name='name',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='users',
            field=models.ManyToManyField(blank=True, default=1, to=settings.AUTH_USER_MODEL),
        ),
    ]
