# Generated by Django 3.0.6 on 2020-06-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0008_auto_20200613_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplan',
            old_name='name',
            new_name='strMeal',
        ),
    ]
