# Generated by Django 3.0.6 on 2020-06-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0009_auto_20200614_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='mealType',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
