# Generated by Django 3.0.6 on 2020-06-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0011_mealplan_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='Ingredients',
        ),
    ]
