# Generated by Django 3.0.6 on 2020-06-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_delivery_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=100)),
                ('img', models.CharField(default='None', max_length=100)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('state', models.BooleanField(default=False)),
                ('delivery_id', models.ManyToManyField(to='deliveries.Delivery')),
            ],
        ),
    ]
