# Generated by Django 3.0.6 on 2020-06-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0002_remove_shoppinglist_img2'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='img2',
            field=models.ImageField(blank=True, default='https://static.openfoodfacts.org/images/products/00356152/front_en.3.full.jpg', null=True, upload_to=''),
        ),
    ]
