# Generated by Django 3.0.6 on 2020-06-08 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0003_shoppinglist_img2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='img2',
        ),
    ]
