# Generated by Django 3.0.6 on 2020-06-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_delivery_user'),
        ('shoppings', '0006_shoppinglist_delivery_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='delivery_id',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='delivery_id',
            field=models.ManyToManyField(to='deliveries.Delivery'),
        ),
    ]
