# Generated by Django 3.0.6 on 2020-06-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0007_auto_20200612_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='delivery_id',
        ),
    ]
