# Generated by Django 3.0.6 on 2020-06-13 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_delete_shoppinglist'),
        ('shoppings', '0009_shoppinglist_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglist', to='deliveries.Delivery'),
        ),
    ]
