# Generated by Django 3.0.6 on 2020-06-13 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
