# Generated by Django 3.0.7 on 2020-06-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplan',
            old_name='id',
            new_name='idMeal',
        ),
        migrations.RenameField(
            model_name='mealplan',
            old_name='mealType',
            new_name='strIngredient1',
        ),
        migrations.RenameField(
            model_name='mealplan',
            old_name='name',
            new_name='strIngredient10',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='intMeasure1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='intMeasure10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='intMeasure11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='intMeasure12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='intMeasure13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='intMeasure14',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='intMeasure15',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='intMeasure16',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='intMeasure17',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='intMeasure18',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='intMeasure19',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='intMeasure2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='intMeasure20',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='intMeasure3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='intMeasure4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='intMeasure5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='intMeasure6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='intMeasure7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='intMeasure8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='intMeasure9',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient11',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient12',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient13',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient14',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient15',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient16',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient17',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient18',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient19',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient2',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient20',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient3',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient4',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient5',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient6',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient7',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient8',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient9',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strInstructions',
            field=models.CharField(default='None', max_length=3000),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMeal',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMealThumb',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
