# Generated by Django 3.0.7 on 2020-06-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0002_auto_20200613_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplan',
            old_name='idMeal',
            new_name='id',
        ),
    ]
