# Generated by Django 3.0.6 on 2020-06-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0004_auto_20200607_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplan',
            old_name='id',
            new_name='idMeal',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient1',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient10',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient11',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient12',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient13',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient14',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient15',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient16',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient17',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient18',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient19',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient2',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient20',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient3',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient4',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient5',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient6',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient7',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient8',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strIngredient9',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strInstructions',
            field=models.CharField(default='None', max_length=2000),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMealThumb',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMeasure1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMeasure10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMeasure11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMeasure12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMeasure13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMeasure14',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMeasure15',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMeasure16',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMeasure17',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMeasure18',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMeasure19',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMeasure2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMeasure20',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMeasure3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMeasure4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMeasure5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMeasure6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMeasure7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMeasure8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='strMeasure9',
            field=models.IntegerField(default=0),
        ),
    ]
