# Generated by Django 3.0.7 on 2020-06-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0009_auto_20200613_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplan',
            old_name='strMeals',
            new_name='strMeal',
        ),
    ]
