# Generated by Django 3.0.7 on 2020-06-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0011_auto_20200613_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='strMeal',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strMealThumb',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
