# Generated by Django 3.0.7 on 2020-06-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0012_auto_20200613_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='strIngredient1',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strIngredient10',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strIngredient11',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strIngredient12',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strIngredient13',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strIngredient14',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strIngredient15',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strIngredient16',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strIngredient17',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strIngredient18',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strIngredient19',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strIngredient2',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strIngredient20',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strIngredient3',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strIngredient4',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strIngredient5',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strIngredient6',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strIngredient7',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strIngredient8',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='strIngredient9',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
