# Generated by Django 3.0.7 on 2020-06-13 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0014_auto_20200613_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplan',
            old_name='strMealThumb',
            new_name='img',
        ),
    ]
