# Generated by Django 3.0.6 on 2020-06-15 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('shoppinglist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='None', max_length=100)),
                ('img', models.CharField(default='None', max_length=100)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('state', models.BooleanField(default=False)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglist', to='deliveries.Delivery')),
            ],
        ),
    ]
