# Generated by Django 3.0.6 on 2020-06-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0004_remove_shoppinglist_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='img',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
