# Generated by Django 3.0.6 on 2020-06-12 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_delete_shoppinglist'),
        ('shoppings', '0008_remove_shoppinglist_delivery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deliveries.Delivery'),
        ),
    ]
