# Generated by Django 3.0.6 on 2020-05-27 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='deliveryadress',
        ),
    ]
