# Generated by Django 3.0.6 on 2020-06-08 08:19

import deliveries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_delivery_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=deliveries.models.upload_path),
        ),
        migrations.AddField(
            model_name='delivery',
            name='name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
