# Generated by Django 3.0.6 on 2020-05-27 02:27

import django.contrib.auth.base_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_delivery_deliveryadress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='deliveryadress',
            field=models.CharField(default=django.contrib.auth.base_user.AbstractBaseUser.get_username, max_length=100),
        ),
    ]
