# Generated by Django 3.0.6 on 2020-06-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_remove_meals_vitaminc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='strInstructions',
            field=models.CharField(default=None, max_length=400),
        ),
        migrations.AlterField(
            model_name='meals',
            name='strMealThumb',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
