# Generated by Django 3.0.6 on 2020-05-27 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200527_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='healthState',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
    ]
