# Generated by Django 3.0.6 on 2020-06-15 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0012_remove_mealplan_ingredients'),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='mealplan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='mealplans.MealPlan'),
        ),
    ]
