# Generated by Django 3.0.6 on 2020-06-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0012_remove_mealplan_ingredients'),
        ('ingredients', '0002_ingredients_mealplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='mealplan',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='mealplan',
            field=models.ManyToManyField(null=True, related_name='ingredients', to='mealplans.MealPlan'),
        ),
    ]
