# Generated by Django 3.0.6 on 2020-06-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0003_shoppinglist_user'),
        ('ingredients', '0003_auto_20200615_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='shoppingList',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='shoppingList',
            field=models.ManyToManyField(null=True, related_name='ingredients', to='shoppings.ShoppingList'),
        ),
    ]
