# Generated by Django 3.0.6 on 2020-06-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='None', max_length=100)),
                ('img', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
