# Generated by Django 3.0.6 on 2020-06-08 02:27

from django.db import migrations, models
import shoppings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='None', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.BooleanField(default=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to=shoppings.models.upload_path)),
            ],
        ),
    ]
