# Generated by Django 3.0.6 on 2020-06-08 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_delivery_user'),
        ('shoppings', '0002_shoppinglist_delivery_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='delivery_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deliveries.Delivery'),
        ),
    ]
