# Generated by Django 3.0.6 on 2020-05-27 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('deliverydate', models.DateTimeField(default=django.utils.timezone.now)),
                ('delcreateddate', models.DateTimeField(auto_now_add=True)),
                ('deliveryadress', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
