# Generated by Django 3.0.6 on 2020-06-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_auto_20200613_0021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
